"""add_refresh_token_to_users

Revision ID: 8571c10fd641
Revises: b827931122b3
Create Date: 2026-04-01 11:00:24.959703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8571c10fd641'
down_revision: Union[str, Sequence[str], None] = 'b827931122b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # usage_records.duration_minutes — 이미 있으면 스킵
    existing_usage_cols = [c['name'] for c in inspector.get_columns('usage_records')]
    if 'duration_minutes' not in existing_usage_cols:
        with op.batch_alter_table('usage_records', schema=None) as batch_op:
            batch_op.add_column(sa.Column('duration_minutes', sa.Float(), nullable=True, comment='오디오 길이 (분, STT 전용)'))

    # users.refresh_token, refresh_token_expires_at — 이미 있으면 스킵
    existing_user_cols = [c['name'] for c in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'refresh_token' not in existing_user_cols:
            batch_op.add_column(sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='리프레시 토큰'))
            batch_op.create_index(batch_op.f('ix_users_refresh_token'), ['refresh_token'], unique=True)
        if 'refresh_token_expires_at' not in existing_user_cols:
            batch_op.add_column(sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='리프레시 토큰 만료 시각'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_refresh_token'))
        batch_op.drop_column('refresh_token_expires_at')
        batch_op.drop_column('refresh_token')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###
