"""add_user_auth_and_usage

Revision ID: a6c5aa937945
Revises: 
Create Date: 2026-03-12 15:24:45.509506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c5aa937945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False, comment='Google sub ID'),
    sa.Column('email', sa.String(length=500), nullable=False, comment='Google 이메일'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='표시 이름'),
    sa.Column('picture', sa.String(length=1000), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='가입 시각'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='마지막 로그인'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='stt 또는 summarize'),
    sa.Column('cost', sa.Float(), nullable=True, comment='API 비용 (USD)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='사용 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_user_action_date', ['user_id', 'action_type', 'created_at'], unique=False)

    with op.batch_alter_table('summary_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), nullable=True, comment='입력 토큰 수'))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), nullable=True, comment='출력 토큰 수'))
        batch_op.add_column(sa.Column('llm_cost', sa.Float(), nullable=True, comment='LLM API 비용 (USD)'))

    with op.batch_alter_table('transcript_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='소유자 ID'))
        batch_op.add_column(sa.Column('project_name', sa.String(length=500), nullable=True, comment='프로젝트명'))
        batch_op.add_column(sa.Column('meeting_title', sa.String(length=500), nullable=True, comment='회의 제목'))
        batch_op.add_column(sa.Column('attendees', sa.Text(), nullable=True, comment='참석자 목록'))
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=True, comment='관련 키워드'))
        batch_op.add_column(sa.Column('stt_cost', sa.Float(), nullable=True, comment='STT API 비용 (USD)'))
        batch_op.create_index(batch_op.f('ix_transcript_records_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_transcript_records_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transcript_records_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transcript_records_user_id'))
        batch_op.drop_column('stt_cost')
        batch_op.drop_column('keywords')
        batch_op.drop_column('attendees')
        batch_op.drop_column('meeting_title')
        batch_op.drop_column('project_name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('summary_records', schema=None) as batch_op:
        batch_op.drop_column('llm_cost')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_action_date')
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_id'))

    op.drop_table('usage_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
